module.exports = {
  content: [
    "./public/index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffe089",
        "on-tertiary-container": "#5a4700",
        "on-surface-variant": "#acaab0",
        "inverse-on-surface": "#555459",
        "on-surface": "#fcf8fe",
        "secondary-container": "#006a67",
        "surface-container-low": "#131317",
        "secondary-fixed": "#5af9f3",
        "surface-variant": "#25252b",
        "surface-bright": "#2c2b32",
        "error": "#ff6e84",
        "on-error": "#490013",
        "outline": "#76757a",
        "outline-variant": "#48474c",
        "secondary-dim": "#46eae5",
        "surface-container": "#19191e",
        "on-secondary-fixed-variant": "#006764",
        "surface-container-highest": "#25252b",
        "surface-container-lowest": "#000000",
        "primary": "#aca3ff",
        "inverse-surface": "#fcf8fe",
        "surface-dim": "#0e0e12",
        "error-container": "#a70138",
        "tertiary-dim": "#efc117",
        "on-primary-fixed-variant": "#250094",
        "surface": "#0e0e12",
        "secondary": "#5af9f3",
        "inverse-primary": "#5948d3",
        "on-primary": "#27009a",
        "on-error-container": "#ffb2b9",
        "on-tertiary": "#644f00",
        "on-secondary-fixed": "#004746",
        "error-dim": "#d73357",
        "on-secondary-container": "#dafffc",
        "primary-container": "#9e93ff",
        "tertiary-container": "#ffcf2a",
        "on-primary-container": "#1d007a",
        "on-tertiary-fixed-variant": "#655000",
        "surface-container-high": "#1f1f24",
        "secondary-fixed-dim": "#46eae5",
        "tertiary-fixed-dim": "#efc117",
        "on-background": "#fcf8fe",
        "surface-tint": "#aca3ff",
        "primary-fixed-dim": "#8f83ff",
        "tertiary-fixed": "#ffcf2a",
        "primary-fixed": "#9e93ff",
        "on-tertiary-fixed": "#433400",
        "background": "#0e0e12",
        "on-primary-fixed": "#000000",
        "primary-dim": "#6f5fea",
        "on-secondary": "#005c59"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
