// Page mapping - converts folder names to route paths and component names
export const pageMapping = {
  'role_selection_1': { path: '/role-selection', component: 'RoleSelection', type: 'auth' },
  'role_selection_2': { path: '/role-selection-2', component: 'RoleSelection2', type: 'auth' },
  'student_portal_auth': { path: '/student/login', component: 'StudentAuth', type: 'auth' },
  'student_portal_registration': { path: '/student/register', component: 'StudentRegister', type: 'auth' },
  'parent_portal_auth': { path: '/parent/login', component: 'ParentAuth', type: 'auth' },
  'parent_portal_registration': { path: '/parent/register', component: 'ParentRegister', type: 'auth' },
  'student_dashboard_1': { path: '/student/dashboard', component: 'StudentDashboard', type: 'student' },
  'student_dashboard_2': { path: '/student/dashboard-2', component: 'StudentDashboard2', type: 'student' },
  'student_hero_forge_avatar_shop': { path: '/student/avatar-shop', component: 'AvatarShop', type: 'student' },
  'student_hero_wardrobe_1': { path: '/student/wardrobe', component: 'Wardrobe', type: 'student' },
  'student_hero_wardrobe_2': { path: '/student/wardrobe-2', component: 'Wardrobe2', type: 'student' },
  'student_hero_wardrobe_3': { path: '/student/wardrobe-3', component: 'Wardrobe3', type: 'student' },
  'student_hero_wardrobe_4': { path: '/student/wardrobe-4', component: 'Wardrobe4', type: 'student' },
  'student_hero_wardrobe_friendly_edition': { path: '/student/wardrobe-friendly', component: 'WardrobeFriendly', type: 'student' },
  'student_store_marketplace': { path: '/student/marketplace', component: 'Marketplace', type: 'student' },
  'student_online_library': { path: '/student/library', component: 'Library', type: 'student' },
  'student_wallet_gift_requests_1': { path: '/student/gifts', component: 'GiftRequests', type: 'student' },
  'student_wallet_gift_requests_2': { path: '/student/gifts-2', component: 'GiftRequests2', type: 'student' },
  'study_session_active_1': { path: '/study-session', component: 'StudySession', type: 'student' },
  'study_session_active_2': { path: '/study-session-2', component: 'StudySession2', type: 'student' },
  'study_session_active_3': { path: '/study-session-3', component: 'StudySession3', type: 'student' },
  'study_session_active_4': { path: '/study-session-4', component: 'StudySession4', type: 'student' },
  'parent_dashboard_1': { path: '/parent/dashboard', component: 'ParentDashboard', type: 'parent' },
  'parent_dashboard_2': { path: '/parent/dashboard-2', component: 'ParentDashboard2', type: 'parent' },
  'parent_gift_card_manager_1': { path: '/parent/gift-manager', component: 'GiftManager', type: 'parent' },
  'parent_gift_card_manager_2': { path: '/parent/gift-manager-2', component: 'GiftManager2', type: 'parent' },
  'parent_library_manager_1': { path: '/parent/library-manager', component: 'LibraryManager', type: 'parent' },
  'parent_treasury_tips': { path: '/parent/treasury-tips', component: 'TreasuryTips', type: 'parent' },
  'child_detailed_activity_report': { path: '/parent/child-activity', component: 'ChildDetailedActivity', type: 'parent' },
  'parent_control_settings': { path: '/parent/control-settings', component: 'ParentControlSettings', type: 'parent' },
  'user_settings_profile_editor': { path: '/settings', component: 'Settings', type: 'common' },
  'direct_chat_social_hub': { path: '/chat', component: 'Chat', type: 'common' },
  'community_classes': { path: '/community-classes', component: 'CommunityClasses', type: 'common' },
  'digital_hero_forge_rpg_edition': { path: '/hero-forge', component: 'HeroForge', type: 'common' },
  'eduskeleton_customizer_trading_hub': { path: '/trading-hub', component: 'TradingHub', type: 'common' },
  'guardian_lab_hero_customizer': { path: '/hero-customizer', component: 'HeroCustomizer', type: 'common' },
  'hero_trading_hub_elite_gear': { path: '/elite-gear', component: 'EliteGear', type: 'common' },
  'educoin_role_selection_flow': { path: '/role-flow', component: 'RoleFlow', type: 'auth' },
};

export default pageMapping;
